photo_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	resources :comments
  end
  root 'posts#index'





#=========================
# RAKED ROUTES
#=========================
                
#                   Prefix Verb   URI Pattern                                 Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                    devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                    devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                   devise/sessions#destroy
#            user_password POST   /users/password(.:format)                   devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)               devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)              devise/passwords#edit
#                          PATCH  /users/password(.:format)                   devise/passwords#update
#                          PUT    /users/password(.:format)                   devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                     devise/registrations#cancel
#        user_registration POST   /users(.:format)                            devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                    devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                       devise/registrations#edit
#                          PATCH  /users(.:format)                            devise/registrations#update
#                          PUT    /users(.:format)                            devise/registrations#update
#                          DELETE /users(.:format)                            devise/registrations#destroy
#            post_comments GET    /posts/:post_id/comments(.:format)          comments#index
#                          POST   /posts/:post_id/comments(.:format)          comments#create
#         new_post_comment GET    /posts/:post_id/comments/new(.:format)      comments#new
#        edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format) comments#edit
#             post_comment GET    /posts/:post_id/comments/:id(.:format)      comments#show
#                          PATCH  /posts/:post_id/comments/:id(.:format)      comments#update
#                          PUT    /posts/:post_id/comments/:id(.:format)      comments#update
#                          DELETE /posts/:post_id/comments/:id(.:format)      comments#destroy
#                    posts GET    /posts(.:format)                            posts#index
#                          POST   /posts(.:format)                            posts#create
#                 new_post GET    /posts/new(.:format)                        posts#new
#                edit_post GET    /posts/:id/edit(.:format)                   posts#edit
#                     post GET    /posts/:id(.:format)                        posts#show
#                          PATCH  /posts/:id(.:format)                        posts#update
#                          PUT    /posts/:id(.:format)                        posts#update
#                          DELETE /posts/:id(.:format)                        posts#destroy
#                     root GET    /                                           posts#index


end

photo_app/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	# attr_accessible :photo
	has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

photo_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_user


	def index
		@posts = Post.all
		@users = User.all
	end

	def show
		# @posts = current_user.posts
		@posts = User.find(params[:id]).posts
		

		# @comment.post_id = @post.id
	end

	def create
		caption = post_params[:caption]
		photo = post_params[:photo]
		if photo.blank? !=false
			flash[:error] = "GOOBY GOOBY GOO"
			redirect_to :back
		else
			@post = Post.create(:caption => caption, :photo => photo, :user_id => @user.id)
			# <%=photo_file_name.url(:medium)%>
			# binding.pry
			redirect_to '/'
		end
	end

	def new
		@post = Post.new
		# binding.pry
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end


	private

	def set_user
		@user = User.find_by(id: current_user.id)
	end

	def post_params
		params.require(:post).permit(:caption, :photo)
	end

end

photo_app/app/views/posts/index.html.erb
<html>
<head>
	<title>Welcome</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
</head>
<body>
	<div class = "container">
        <% @posts.reverse.each do |post| %>
        <div class = "">
        	<div><% @user = User.find_by(id: post.user_id)%></div>
            <div class = "username"><%= link_to "@"+@user.email.split("@")[0], post_path(@user.id) %></div>
            <div><%= post.caption %></div>
            <%= image_tag post.photo.url(:medium), :class => "" %>
        </div>
    	<% end %>
    	<div><%= link_to 'New Post', new_post_path %></div>
    </div>

</body>
</html>

photo_app/app/views/posts/new.html.erb
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
</head>
<body>
	<div class = "container">
		<%= form_for @post, :html => { :multipart => true} do |f| %>
		<p>
			<%= f.label :caption %></br>
			<%= f.text_area :caption, :rows => 10, :cols => 50 %>
		</p>
		<p>
			<%= f.file_field :photo %>
		</p>
		<div> <%= flash[:error]%></div>
		<%= f.submit "Submit" %>
		<%end%>
	</div>
</body>
</html>

photo_app/app/views/posts/show.html.erb
<html>
<head>
	<title>Homepage</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
</head>
<body>
	<div class= "container">
	<% @posts.each do |post| %>
		<div class = "column">
			<% @user = User.find_by(id: post.user_id)%>
			<%= image_tag post.photo.url(:medium) %>
		    <div>@<%= @user.email.split("@")[0] %></div>
		    <div><%= post.caption %></div>
		    <div><%= post.created_at %></div>
		   	
		    <%if current_user.id == post.user_id %>
		    <div> <%= link_to 'Delete', post, :method => 'delete', data: { confirm: "Are you sure you want to delete this post? "} %></div>
		    <%end%>
			
			

		<%@comments = Post.find(params[:id]).comments%>
		<% @comments.each do |comm| %>
			<div>
					<% @user2 = User.find_by(id: comm.user_id) %>
					<div>@<%= @user2.email.split("@")[0] %></div>
					<%=comm.body%>
			</div>
			<%end%>







			<%= render partial: 'comments/form' %>








		</div>
	    <% end %>
    	<div><%= link_to 'New Post', new_post_path %></div>
    </div>


</body>
</html>